#!/bin/sh
ssh ubuntu@43.200.57.202 <<EOF
    cd ~/running-map
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 18.9.0
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF